language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "7"
  - "6"
script:
  - "npm run test"
jobs:
deploy:
  provider: npm
  email: outshineamaze@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true